#pragma once

#include "USBHost_t36.h"

#define USBHIDUsageConsumerPageTop (0xc0000)

enum USBHIDUsageConsumerPage : uint16_t {
    Plus10                              = 0x20,     // +10
    Plus100                             = 0x21,     // +100
    AM_PM                               = 0x22,     // AM/PM
    Power                               = 0x30,     // Power
    Reset                               = 0x31,     // Reset
    Sleep                               = 0x32,     // Sleep
    SleepAfter                          = 0x33,     // Sleep After
    SleepMode                           = 0x34,     // Sleep Mode
    Illumination                        = 0x35,     // Illumination
    FunctionButtons                     = 0x36,     // Function Buttons
    Menu                                = 0x40,     // Menu
    MenuPick                            = 0x41,     // Menu  Pick
    MenuUp                              = 0x42,     // Menu Up
    MenuDown                            = 0x43,     // Menu Down
    MenuLeft                            = 0x44,     // Menu Left
    MenuRight                           = 0x45,     // Menu Right
    MenuEscape                          = 0x46,     // Menu Escape
    MenuValueIncrease                   = 0x47,     // Menu Value Increase
    MenuValueDecrease                   = 0x48,     // Menu Value Decrease
    DataOnScreen                        = 0x60,     // Data On Screen
    ClosedCaption                       = 0x61,     // Closed Caption
    ClosedCaptionSelect                 = 0x62,     // Closed Caption Select
    VCR_TV                              = 0x63,     // VCR/TV
    BroadcastMode                       = 0x64,     // Broadcast Mode
    Snapshot                            = 0x65,     // Snapshot
    Still                               = 0x66,     // Still
    Selection                           = 0x80,     // Selection
    AssignSelection                     = 0x81,     // Assign Selection
    ModeStep                            = 0x82,     // Mode Step
    RecallLast                          = 0x83,     // Recall Last
    EnterChannel                        = 0x84,     // Enter Channel
    OrderMovie                          = 0x85,     // Order Movie
    Channel                             = 0x86,     // Channel
    MediaSelection                      = 0x87,     // Media Selection
    MediaSelectComputer                 = 0x88,     // Media Select Computer
    MediaSelectTV                       = 0x89,     // Media Select TV
    MediaSelectWWW                      = 0x8A,     // Media Select WWW
    MediaSelectDVD                      = 0x8B,     // Media Select DVD
    MediaSelectTelephone                = 0x8C,     // Media Select Telephone
    MediaSelectProgramGuide             = 0x8D,     // Media Select Program Guide
    MediaSelectVideoPhone               = 0x8E,     // Media Select Video Phone
    MediaSelectGames                    = 0x8F,     // Media Select Games
    MediaSelectMessages                 = 0x90,     // Media Select Messages
    MediaSelectCD                       = 0x91,     // Media Select CD
    MediaSelectVCR                      = 0x92,     // Media Select VCR
    MediaSelectTuner                    = 0x93,     // Media Select Tuner
    Quit                                = 0x94,     // Quit
    Help                                = 0x95,     // Help
    MediaSelectTape                     = 0x96,     // Media Select Tape
    MediaSelectCable                    = 0x97,     // Media Select Cable
    MediaSelectSatellite                = 0x98,     // Media Select Satellite
    MediaSelectSecurity                 = 0x99,     // Media Select Security
    MediaSelectHome                     = 0x9A,     // Media Select Home
    MediaSelectCall                     = 0x9B,     // Media Select Call
    ChannelIncrement                    = 0x9C,     // Channel Increment
    ChannelDecrement                    = 0x9D,     // Channel Decrement
    MediaSelectSAP                      = 0x9E,     // Media Select SAP
    VCRPlus                             = 0xA0,     // VCR Plus
    Once                                = 0xA1,     // Once
    Daily                               = 0xA2,     // Daily
    Weekly                              = 0xA3,     // Weekly
    Monthly                             = 0xA4,     // Monthly
    Play                                = 0xB0,     // Play
    Pause                               = 0xB1,     // Pause
    Record                              = 0xB2,     // Record
    FastForward                         = 0xB3,     // Fast Forward
    Rewind                              = 0xB4,     // Rewind
    ScanNextTrack                       = 0xB5,     // Scan Next Track
    ScanPreviousTrack                   = 0xB6,     // Scan Previous Track
    Stop                                = 0xB7,     // Stop
    Eject                               = 0xB8,     // Eject
    RandomPlay                          = 0xB9,     // Random Play
    SelectDisC                          = 0xBA,     // Select DisC
    EnterDisc                           = 0xBB,     // Enter Disc
    Repeat                              = 0xBC,     // Repeat
    Tracking                            = 0xBD,     // Tracking
    TrackNormal                         = 0xBE,     // Track Normal
    SlowTracking                        = 0xBF,     // Slow Tracking
    FrameForward                        = 0xC0,     // Frame Forward
    FrameBack                           = 0xC1,     // Frame Back
    Mark                                = 0xC2,     // Mark
    ClearMark                           = 0xC3,     // Clear Mark
    RepeatFromMark                      = 0xC4,     // Repeat From Mark
    ReturnToMark                        = 0xC5,     // Return To Mark
    SearchMarkForward                   = 0xC6,     // Search Mark Forward
    SearchMarkBackwards                 = 0xC7,     // Search Mark Backwards
    CounterReset                        = 0xC8,     // Counter Reset
    ShowCounter                         = 0xC9,     // Show Counter
    TrackingIncrement                   = 0xCA,     // Tracking Increment
    TrackingDecrement                   = 0xCB,     // Tracking Decrement
    Pause_Continue                      = 0xCD,     // Pause/Continue
    Volume                              = 0xE0,     // Volume
    Balance                             = 0xE1,     // Balance
    Mute                                = 0xE2,     // Mute
    Bass                                = 0xE3,     // Bass
    Treble                              = 0xE4,     // Treble
    BassBoost                           = 0xE5,     // Bass Boost
    SurroundMode                        = 0xE6,     // Surround Mode
    Loudness                            = 0xE7,     // Loudness
    MPX                                 = 0xE8,     // MPX
    VolumeUp                            = 0xE9,     // Volume Up
    VolumeDown                          = 0xEA,     // Volume Down
    SpeedSelect                         = 0xF0,     // Speed Select
    PlaybackSpeed                       = 0xF1,     // Playback Speed
    StandardPlay                        = 0xF2,     // Standard Play
    LongPlay                            = 0xF3,     // Long Play
    ExtendedPlay                        = 0xF4,     // Extended Play
    Slow                                = 0xF5,     // Slow
    FanEnable                           = 0x100,    // Fan Enable
    FanSpeed                            = 0x101,    // Fan Speed
    Light                               = 0x102,    // Light
    LightIlluminationLevel              = 0x103,    // Light Illumination Level
    ClimateControlEnable                = 0x104,    // Climate Control Enable
    RoomTemperature                     = 0x105,    // Room Temperature
    SecurityEnable                      = 0x106,    // Security Enable
    FireAlarm                           = 0x107,    // Fire Alarm
    PoliceAlarm                         = 0x108,    // Police Alarm
    BalanceRight                        = 0x150,    // Balance Right
    BalanceLeft                         = 0x151,    // Balance Left
    BassIncrement                       = 0x152,    // Bass Increment
    BassDecrement                       = 0x153,    // Bass Decrement
    TrebleIncrement                     = 0x154,    // Treble Increment
    TrebleDecrement                     = 0x155,    // Treble Decrement
    SpeakerSystem                       = 0x160,    // Speaker System
    ChannelLeft                         = 0x161,    // Channel Left
    ChannelRight                        = 0x162,    // Channel Right
    ChannelCenter                       = 0x163,    // Channel Center
    ChannelFront                        = 0x164,    // Channel Front
    ChannelCenterFront                  = 0x165,    // Channel Center Front
    ChannelSide                         = 0x166,    // Channel Side
    ChannelSurround                     = 0x167,    // Channel Surround
    ChannelLowFrequencyEnhancement      = 0x168,    // Channel Low Frequency Enhancement
    ChannelTop                          = 0x169,    // Channel Top
    ChannelUnknown                      = 0x16A,    // Channel Unknown
    Sub_channel                         = 0x170,    // Sub-channel
    Sub_channelIncrement                = 0x171,    // Sub-channel Increment
    Sub_channelDecrement                = 0x172,    // Sub-channel Decrement
    AlternateAudioIncrement             = 0x173,    // Alternate Audio Increment
    AlternateAudioDecrement             = 0x174,    // Alternate Audio Decrement
    ApplicationLaunchButtons            = 0x180,    // Application Launch Buttons
    ALLaunchButtonConfigurationTool     = 0x181,    // AL Launch Button Configuration Tool
    ALProgrammableButtonConfiguration   = 0x182,    // AL Programmable Button Configuration
    ALConsumerControlConfiguration      = 0x183,    // AL Consumer Control Configuration
    ALWordProcessor                     = 0x184,    // AL Word Processor
    ALTextEditor                        = 0x185,    // AL Text Editor
    ALSpreadsheet                       = 0x186,    // AL Spreadsheet
    ALGraphicsEditor                    = 0x187,    // AL Graphics Editor
    ALPresentationApp                   = 0x188,    // AL Presentation App
    ALDatabaseApp                       = 0x189,    // AL Database App
    ALEmailReader                       = 0x18A,    // AL Email Reader
    ALNewsreader                        = 0x18B,    // AL Newsreader
    ALVoicemail                         = 0x18C,    // AL Voicemail
    ALContacts_AddressBook              = 0x18D,    // AL Contacts/Address Book
    ALCalendar_Schedule                 = 0x18E,    // AL Calendar/Schedule
    ALTask_ProjectManager               = 0x18F,    // AL Task/Project Manager
    ALLog_Journal_Timecard              = 0x190,    // AL Log/Journal/Timecard
    ALCheckbook_Finance                 = 0x191,    // AL Checkbook/Finance
    ALCalculator                        = 0x192,    // AL Calculator
    ALA_VCapture_Playback               = 0x193,    // AL A/V Capture/Playback
    ALLocalMachineBrowser               = 0x194,    // AL Local Machine Browser
    ALLAN_WANBrowser                    = 0x195,    // AL LAN/WAN Browser
    ALInternetBrowser                   = 0x196,    // AL Internet Browser
    ALRemoteNetworking_ISPConnect       = 0x197,    // AL Remote Networking/ISP Connect
    ALNetworkConference                 = 0x198,    // AL Network Conference
    ALNetworkChat                       = 0x199,    // AL Network Chat
    ALTelephony_Dialer                  = 0x19A,    // AL Telephony/Dialer
    ALLogon                             = 0x19B,    // AL Logon
    ALLogoff                            = 0x19C,    // AL Logoff
    ALLogon_Logoff                      = 0x19D,    // AL Logon/Logoff
    ALTerminalLock_Screensaver          = 0x19E,    // AL Terminal Lock/Screensaver
    ALControlPanel                      = 0x19F,    // AL Control Panel
    ALCommandLineProcessor_Run          = 0x1A0,    // AL Command Line Processor/Run
    ALProcess_TaskManager               = 0x1A1,    // AL Process/Task Manager
    ALSelectTast_Application            = 0x1A2,    // AL Select Tast/Application
    ALNextTask_Application              = 0x1A3,    // AL Next Task/Application
    ALPreviousTask_Application          = 0x1A4,    // AL Previous Task/Application
    ALPreemptiveHaltTask_Application    = 0x1A5,    // AL Preemptive Halt Task/Application
    GenericGUIApplicationControls       = 0x200,    // Generic GUI Application Controls
    ACNew                               = 0x201,    // AC New
    ACOpen                              = 0x202,    // AC Open
    ACClose                             = 0x203,    // AC Close
    ACExit                              = 0x204,    // AC Exit
    ACMaximize                          = 0x205,    // AC Maximize
    ACMinimize                          = 0x206,    // AC Minimize
    ACSave                              = 0x207,    // AC Save
    ACPrint                             = 0x208,    // AC Print
    ACProperties                        = 0x209,    // AC Properties
    ACUndo                              = 0x21A,    // AC Undo
    ACCopy                              = 0x21B,    // AC Copy
    ACCut                               = 0x21C,    // AC Cut
    ACPaste                             = 0x21D,    // AC Paste
    ACSelectAll                         = 0x21E,    // AC Select All
    ACFind                              = 0x21F,    // AC Find
    ACFindandReplace                    = 0x220,    // AC Find and Replace
    ACSearch                            = 0x221,    // AC Search
    ACGoTo                              = 0x222,    // AC Go To
    ACHome                              = 0x223,    // AC Home
    ACBack                              = 0x224,    // AC Back
    ACForward                           = 0x225,    // AC Forward
    ACStop                              = 0x226,    // AC Stop
    ACRefresh                           = 0x227,    // AC Refresh
    ACPreviousLink                      = 0x228,    // AC Previous Link
    ACNextLink                          = 0x229,    // AC Next Link
    ACBookmarks                         = 0x22A,    // AC Bookmarks
    ACHistory                           = 0x22B,    // AC History
    ACSubscriptions                     = 0x22C,    // AC Subscriptions
    ACZoomIn                            = 0x22D,    // AC Zoom In
    ACZoomOut                           = 0x22E,    // AC Zoom Out
    ACZoom                              = 0x22F,    // AC Zoom
    ACFullScreenView                    = 0x230,    // AC Full Screen View
    ACNormalView                        = 0x231,    // AC Normal View
    ACViewToggle                        = 0x232,    // AC View Toggle
    ACScrollUp                          = 0x233,    // AC Scroll Up
    ACScrollDown                        = 0x234,    // AC Scroll Down
    ACScroll                            = 0x235,    // AC Scroll
    ACPanLeft                           = 0x236,    // AC Pan Left
    ACPanRight                          = 0x237,    // AC Pan Right
    ACPan                               = 0x238,    // AC Pan
    ACNewWindow                         = 0x239,    // AC New Window
    ACTileHorizontally                  = 0x23A,    // AC Tile Horizontally
    ACTileVertically                    = 0x23B,    // AC Tile Vertically
    ACFormat                            = 0x23C     // AC Format
};

bool const IsConsumerPage(uint32_t top){
    return top == USBHIDUsageConsumerPageTop;
}
